---
- name: Setup Common Infrastructure
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Database Server
  hosts: db
  become: yes
  roles:
    - db

- name: Setup Web Application
  hosts: workers
  become: yes
  roles:
    - web