[workers]
worker-node ansible_host=YOUR_WORKER_PUBLIC_IP internal_ip=10.186.0.2

[db]
db-node ansible_host=YOUR_DB_PUBLIC_IP internal_ip=10.186.0.3

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'