---
- name: Create student user
  ansible.builtin.user:
    name: student
    shell: /bin/bash

- name: Create gradebook file
  ansible.builtin.copy:
    dest: /home/student/gradebook
    content: "8\n"
    owner: student
    group: student
    mode: '0644'

- name: Create teacher user
  ansible.builtin.user:
    name: teacher
    password: "{{ '12345678' | password_hash('sha512') }}"
    groups: sudo
    append: yes
    shell: /bin/bash