---
- name: Створити користувача teacher (пароль 12345678)
  user:
    name: teacher
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{ '12345678' | password_hash('sha512', 'mysalt') }}"

- name: Створити директорію для gradebook
  file:
    path: /home/student
    state: directory
    mode: '0755'

- name: Створити файл gradebook із номером варіанту (N=8)
  copy:
    content: "8\n"
    dest: /home/student/gradebook