---
- name: Встановити MariaDB та Python-модулі для Ansible
  apt:
    name: 
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Налаштувати MariaDB слухати свій IP
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: "bind-address = 0.0.0.0"
  notify: Restart MariaDB

- name: Переконатися, що MariaDB запущена
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Створити базу даних mywebapp_db
  mysql_db:
    name: mywebapp_db
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Створити користувача БД та дати права
  mysql_user:
    name: mywebapp_user
    password: supersecretpassword
    priv: 'mywebapp_db.*:ALL'
    host: "{{ hostvars['worker-node']['internal_ip'] }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock