#cloud-config
users:
  - name: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINw3u9xSiLAgkPRQCj2ofHE2W9nHIAy5Fqv3H3pFkf5p djalb@LENOVO-B560